### ISSUE TITLE
Alamofire 4 + Swift3 support

### ISSUE THREAD

**Issue by gmenel** [starboychina/AlamofireSwiftyJSON#1]
This becomes uninstallable as a pod when run in conjunction with Alamofire4 on the swift3 train.
I've manually integrated the file and tuned it a bit, but might be worth an update for other peeps like me.

**Comment by ghost** [comment]
Yes update for Alamofire 4 and Swift 3 please.

**Comment by Xinguang** [comment]
Thank you for your attention to this matter.

I have landed Swift3 support in master branch, also Swift2.2 support in swift2.2 branch.

### Upgrade to Swift3

With CocoaPods

Update your Podfile

``` podfile
pod 'AlamofireSwiftyJSON', '0.2.0'
```

Also, at the time of writing, CocoaPods 1.1 is still not released.
So in order to get it working with Xcode8, we need the rc version

``` shell
gem install cocoapods -v 1.1.0.rc.2
```

Carthage

``` Cartfile
github "starboychina/AlamofireSwiftyJSON" "0.2.0"
```
